Repository Automattic/Automattic-Tracks-iOS, pull requests merged in 2020-03, with the labels that each got.

#119 Migrate to Swift5
  Automattic-Tracks-iOS.xcodeproj/project.pbxproj
  Automattic-Tracks-iOS.xcodeproj/xcshareddata/xcschemes/Automattic-Tracks-OSX.xcscheme
  Automattic-Tracks-iOS.xcodeproj/xcshareddata/xcschemes/Automattic-Tracks-iOS.xcscheme
  Automattic-Tracks-iOS/TracksConstants.m
Labels: enhancement

#120 Implement Log Encryption
  .circleci/config.yml
  Automattic-Tracks-iOS.podspec
  Automattic-Tracks-iOS.xcodeproj/project.pbxproj
  Automattic-Tracks-iOS/Event Logging/LogEncryptor.swift
  Automattic-Tracks-iOS/Extensions/FileHandle+Extensions.swift
  Automattic-Tracks-iOS/LogFile.swift
  Automattic-Tracks-iOSTests/EncryptedLog.swift
  Automattic-Tracks-iOSTests/Event Logging/LogEncryptionTests.swift
  Automattic-Tracks-iOSTests/Extensions.swift
  Automattic-Tracks-iOSTests/LogFile+TestHelpers.swift
  Podfile
  Podfile.lock
Labels: enhancement

#123 Fixes code signing during development
  Automattic-Tracks-iOS.xcodeproj/project.pbxproj
Labels: bug

#125 Merge release/0.4.4 back into develop
  Automattic-Tracks-iOS/TracksConstants.m
Labels: Releases

#128 Add Swiftlint
  .hound.yml
  .swiftlint.yml
  Automattic-Tracks-iOS/Crash Logging/CrashLogging.swift
  Automattic-Tracks-iOS/Crash Logging/CrashLoggingDataProvider.swift
  Automattic-Tracks-iOS/Crash Logging/TestHelpers.swift
  Automattic-Tracks-iOS/Model/TracksUser.swift
  Automattic-Tracks-iOSTests/Test Helpers/Extensions.swift
  Automattic-Tracks-iOSTests/Tests/CrashLoggingTests.swift
  Automattic-Tracks-iOSTests/Tests/TracksServiceRemoteTests.swift
  TracksDemo/TracksDemo Mac/AppDelegate.swift
  TracksDemo/TracksDemo Mac/ViewController.swift
Labels: enhancement

#127 Add event logging upload
  Automattic-Tracks-iOS.podspec
  Automattic-Tracks-iOS.xcodeproj/project.pbxproj
  Automattic-Tracks-iOS/Event Logging/EventLoggingDataSource.swift
  Automattic-Tracks-iOS/Event Logging/EventLoggingDelegate.swift
  Automattic-Tracks-iOS/Event Logging/EventLoggingUploadManager.swift
  Automattic-Tracks-iOS/Extensions/FileManager+Extensions.swift
  Automattic-Tracks-iOS/Model/EventLoggingFileUploadError.swift
  Automattic-Tracks-iOS/Model/LogFile.swift
  Automattic-Tracks-iOS/Services/EventLoggingNetworkService.swift
  Automattic-Tracks-iOS/Services/EventLoggingUploadQueue.swift
  Automattic-Tracks-iOSTests/Test Helpers/Extensions.swift
  Automattic-Tracks-iOSTests/Test Helpers/LogFile+TestHelpers.swift
  Automattic-Tracks-iOSTests/Test Helpers/Mocks.swift
  Automattic-Tracks-iOSTests/Test Helpers/NetworkRequestMocks.swift
  Automattic-Tracks-iOSTests/Tests/Event Logging/EventLoggingNetworkServiceTests.swift
  Automattic-Tracks-iOSTests/Tests/Event Logging/EventLoggingUploadManagerTests.swift
  Automattic-Tracks-iOSTests/Tests/Event Logging/EventLoggingUploadQueueTests.swift
  Automattic-Tracks-iOSTests/Tests/Event Logging/LogFileTests.swift
Labels: enhancement
