Repository Automattic/Automattic-Tracks-iOS, pull requests merged in 2021-01, with the labels that each got.

#160 Updates Sodium to 0.9.1 and removes workaround for M1 builds
  .ruby-version
  Automattic-Tracks-iOS.podspec
  Automattic-Tracks-iOS.xcodeproj/project.pbxproj
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  TracksDemo/Podfile
  TracksDemo/Podfile.lock
  TracksDemo/TracksDemo.xcodeproj/project.pbxproj
Labels: enhancement

#164 Add macOS support for ExPlat
  Automattic-Tracks-iOS.xcodeproj/project.pbxproj
  Automattic-Tracks-iOS/ABTesting/ExPlat.swift
Labels: bug

#166 Update Sentry to v6
  .gitignore
  Automattic-Tracks-iOS.podspec
  Automattic-Tracks-iOS.xcodeproj/project.pbxproj
  Automattic-Tracks-iOS/Automattic-Tracks-Bridging-Header.h
  Automattic-Tracks-iOS/Crash Logging/CrashLogging.swift
  Automattic-Tracks-iOS/Crash Logging/CrashLoggingDataProvider.swift
  Automattic-Tracks-iOS/Crash Logging/SentryClient+Shim.h
  Automattic-Tracks-iOS/Crash Logging/SentryClient+Shim.m
  Automattic-Tracks-iOS/Crash Logging/SentryEventSerializer.swift
  Automattic-Tracks-iOS/Crash Logging/SentryTestError.swift
  Automattic-Tracks-iOS/Crash Logging/TestHelpers.swift
  Automattic-Tracks-iOS/Event Logging/EventLogging+Sentry.swift
  Automattic-Tracks-iOS/Event Logging/EventLogging.swift
  Automattic-Tracks-iOS/Model/TracksUser.swift
  Automattic-Tracks-iOS/UI/Crash Logging/CrashLoggingView.swift
  Automattic-Tracks-iOSTests/Tests/CrashLoggingTests.swift
  Automattic-Tracks-iOSTests/Tests/SentryEventSerializerTests.swift
  Podfile
  Podfile.lock
  TracksDemo/Podfile
  TracksDemo/Podfile.lock
  TracksDemo/Shared/CrashLoggingDataSource.swift
  TracksDemo/Shared/Secrets.example.swift
  TracksDemo/TracksDemo Mac/Base.lproj/Main.storyboard
  TracksDemo/TracksDemo Mac/CrashLoggingRootViewController.swift
  TracksDemo/TracksDemo.xcodeproj/project.pbxproj
  TracksDemo/TracksDemo.xcodeproj/xcshareddata/xcschemes/TracksDemo Mac.xcscheme
  TracksDemo/TracksDemo.xcodeproj/xcshareddata/xcschemes/TracksDemo.xcscheme
  TracksDemo/TracksDemo/Base.lproj/Main.storyboard
  TracksDemo/TracksDemo/CrashLoggingRootViewController.swift
  TracksDemo/TracksDemo/TracksDemo-Bridging-Header.h
Labels: enhancement

#168 Cut 0.8.0
  Automattic-Tracks-iOS/TracksConstants.m
  TracksDemo/Podfile.lock
Labels: Releases

#169 Merge 0.8.0 into trunk
  .gitignore
  .ruby-version
  Automattic-Tracks-iOS.podspec
  Automattic-Tracks-iOS.xcodeproj/project.pbxproj
  Automattic-Tracks-iOS/ABTesting/ABTesting.swift
  Automattic-Tracks-iOS/ABTesting/ExPlat.swift
  Automattic-Tracks-iOS/Automattic-Tracks-Bridging-Header.h
  Automattic-Tracks-iOS/Crash Logging/CrashLogging.swift
  Automattic-Tracks-iOS/Crash Logging/CrashLoggingDataProvider.swift
  Automattic-Tracks-iOS/Crash Logging/SentryClient+Shim.h
  Automattic-Tracks-iOS/Crash Logging/SentryClient+Shim.m
  Automattic-Tracks-iOS/Crash Logging/SentryEventSerializer.swift
  Automattic-Tracks-iOS/Crash Logging/SentryTestError.swift
  Automattic-Tracks-iOS/Crash Logging/TestHelpers.swift
  Automattic-Tracks-iOS/Event Logging/EventLogging+Sentry.swift
  Automattic-Tracks-iOS/Event Logging/EventLogging.swift
  Automattic-Tracks-iOS/Model/TracksUser.swift
  Automattic-Tracks-iOS/TracksConstants.m
  Automattic-Tracks-iOS/UI/Crash Logging/CrashLoggingView.swift
  Automattic-Tracks-iOSTests/Mock Data/explat-assignments.json
  Automattic-Tracks-iOSTests/Tests/ABTesting/ExPlatServiceTests.swift
  Automattic-Tracks-iOSTests/Tests/ABTesting/ExPlatTests.swift
  Automattic-Tracks-iOSTests/Tests/CrashLoggingTests.swift
  Automattic-Tracks-iOSTests/Tests/SentryEventSerializerTests.swift
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  README.md
  TracksDemo/Podfile
  TracksDemo/Podfile.lock
  TracksDemo/Shared/CrashLoggingDataSource.swift
  TracksDemo/Shared/Secrets.example.swift
  TracksDemo/TracksDemo Mac/Base.lproj/Main.storyboard
  TracksDemo/TracksDemo Mac/CrashLoggingRootViewController.swift
  TracksDemo/TracksDemo.xcodeproj/project.pbxproj
  TracksDemo/TracksDemo.xcodeproj/xcshareddata/xcschemes/TracksDemo Mac.xcscheme
  TracksDemo/TracksDemo.xcodeproj/xcshareddata/xcschemes/TracksDemo.xcscheme
  TracksDemo/TracksDemo/Base.lproj/Main.storyboard
  TracksDemo/TracksDemo/CrashLoggingRootViewController.swift
  TracksDemo/TracksDemo/TracksDemo-Bridging-Header.h
Labels: Releases
