Repository Automattic/Automattic-Tracks-iOS, pull requests merged in 2023-11, with the labels that each got.

#265 Use Xcode 15.0.1
  .buildkite/pipeline.yml
  .buildkite/validate_podspec_annotation.md
  Tests/Tests/Event Logging/EventLoggingTests.swift
Labels: enhancement

#269 Update Cocoapods and Fastlane
  Gemfile.lock
  Tests/Tests/Event Logging/EventLoggingTests.swift
Labels: dependencies

#268 Bump version to 3.0.0
  Automattic-Tracks-iOS.podspec
  CHANGELOG.md
  Gemfile.lock
  Sources/Model/ObjC/Constants/TracksConstants.m
  Tests/Tests/Event Logging/EventLoggingTests.swift
Labels: Releases
